name: Terraform  Workflow Pipeline
run-name: "Terraform Pipeline"
env:
  TF_VERSION: 1.3.5
on:   
  push:
    branches:
    - main
    paths: 
    - terraform-actions/modules/*
  pull_request: 
    branches:
    - main
    paths: 
    - terraform-actions/modules/*
jobs:

  provision_resources:
    name: "Provisioning Infra"
    environment: dev
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
    - uses: actions/checkout@v3

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}
        cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}
  
    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Plan
      run: terraform plan
    
    - name: Terraform Apply
      if: ${{ github.ref_name == 'main' }}
      run: terraform apply --auto-approve
